{
    "data_folder_path": "data/CVE-2022-45199",
    "pull_requests_urls": [
        "https://github.com/python-pillow/Pillow/pull/6700"
    ],
    "cve_name": "CVE-2022-45199",
    "repo": "python-pillow/Pillow",
    "warnings": {
        "cve": "CVE-2022-45199",
        "warnings": [
            {
                "type": "NOT_MODIFIED",
                "file_name": "Tests/images/oom-225817ca0f8c663be7ab4b9e717b02c661e66834.tif",
                "message": "not a modified file (status: FileStatus.ADDED)\n"
            },
            {
                "type": "NO_PATCH",
                "file_name": "Tests/images/oom-225817ca0f8c663be7ab4b9e717b02c661e66834.tif",
                "message": "File has no patch data.\n"
            }
        ]
    },
    "files_extension_stats": {
        ".py": 2,
        ".rst": 1
    },
    "file_number": 3,
    "removed_files_number": 0,
    "added_files_number": 0,
    "nb_lines_affected": 36,
    "private_key_files": [],
    "languages": [
        "Python"
    ]
}