{
    "data_folder_path": "data/CVE-2017-18342",
    "pull_requests_urls": [
        "https://github.com/yaml/pyyaml/pull/74"
    ],
    "cve_name": "CVE-2017-18342",
    "repo": "yaml/pyyaml",
    "warnings": {
        "cve": "CVE-2017-18342",
        "warnings": []
    },
    "files_extension_stats": {
        ".py": 12
    },
    "file_number": 12,
    "removed_files_number": 0,
    "added_files_number": 0,
    "nb_lines_affected": 167,
    "private_key_files": [],
    "languages": [
        "Python"
    ]
}