{
    "data_folder_path": "data/CVE-2021-21273",
    "pull_requests_urls": [
        "https://github.com/matrix-org/synapse/pull/8821"
    ],
    "cve_name": "CVE-2021-21273",
    "repo": "matrix-org/synapse",
    "warnings": {
        "cve": "CVE-2021-21273",
        "warnings": [
            {
                "type": "NOT_MODIFIED",
                "file_name": "changelog.d/8821.bugfix",
                "message": "not a modified file (status: FileStatus.ADDED)\n"
            }
        ]
    },
    "files_extension_stats": {
        ".py": 28,
        ".bugfix": 1,
        ".yaml": 1
    },
    "file_number": 30,
    "removed_files_number": 0,
    "added_files_number": 0,
    "nb_lines_affected": 260,
    "private_key_files": [],
    "languages": [
        "Python"
    ]
}