{
    "data_folder_path": "data/CVE-2022-35920",
    "pull_requests_urls": [
        "https://github.com/sanic-org/sanic/pull/2495"
    ],
    "cve_name": "CVE-2022-35920",
    "repo": "sanic-org/sanic",
    "warnings": {
        "cve": "CVE-2022-35920",
        "warnings": []
    },
    "files_extension_stats": {
        ".py": 2
    },
    "file_number": 2,
    "removed_files_number": 0,
    "added_files_number": 0,
    "nb_lines_affected": 87,
    "private_key_files": [],
    "languages": [
        "Python"
    ]
}