{
    "data_folder_path": "data/CVE-2022-40899",
    "pull_requests_urls": [
        "https://github.com/PythonCharmers/python-future/pull/610"
    ],
    "cve_name": "CVE-2022-40899",
    "repo": "PythonCharmers/python-future",
    "warnings": {
        "cve": "CVE-2022-40899",
        "warnings": []
    },
    "files_extension_stats": {
        ".py": 1
    },
    "file_number": 1,
    "removed_files_number": 0,
    "added_files_number": 0,
    "nb_lines_affected": 18,
    "private_key_files": [],
    "languages": [
        "Python"
    ]
}