{
    "data_folder_path": "data/CVE-2020-8492",
    "pull_requests_urls": [
        "https://github.com/python/cpython/pull/18284"
    ],
    "cve_name": "CVE-2020-8492",
    "repo": "python/cpython",
    "warnings": {
        "cve": "CVE-2020-8492",
        "warnings": [
            {
                "type": "NOT_MODIFIED",
                "file_name": "Misc/NEWS.d/next/Library/2020-03-25-16-02-16.bpo-39503.YmMbYn.rst",
                "message": "not a modified file (status: FileStatus.ADDED)\n"
            },
            {
                "type": "NOT_MODIFIED",
                "file_name": "Misc/NEWS.d/next/Security/2020-01-30-16-15-29.bpo-39503.B299Yq.rst",
                "message": "not a modified file (status: FileStatus.ADDED)\n"
            }
        ]
    },
    "files_extension_stats": {
        ".py": 2,
        ".rst": 2
    },
    "file_number": 4,
    "removed_files_number": 0,
    "added_files_number": 0,
    "nb_lines_affected": 167,
    "private_key_files": [],
    "languages": [
        "Python"
    ]
}