{
    "data_folder_path": "data/CVE-2022-21187",
    "pull_requests_urls": [
        "https://github.com/vcs-python/libvcs/pull/306"
    ],
    "cve_name": "CVE-2022-21187",
    "repo": "vcs-python/libvcs",
    "warnings": {
        "cve": "CVE-2022-21187",
        "warnings": []
    },
    "files_extension_stats": {
        ".py": 2
    },
    "file_number": 3,
    "removed_files_number": 0,
    "added_files_number": 0,
    "nb_lines_affected": 37,
    "private_key_files": [],
    "languages": [
        "Python"
    ]
}