{
    "data_folder_path": "data/CVE-2016-9189",
    "pull_requests_urls": [
        "https://github.com/python-pillow/Pillow/pull/2146/commits/c50ebe6459a131a1ea8ca531f10da616d3ceaa0f"
    ],
    "cve_name": "CVE-2016-9189",
    "repo": "python-pillow/Pillow",
    "warnings": {
        "cve": "CVE-2016-9189",
        "warnings": [
            {
                "type": "NOT_MODIFIED",
                "file_name": "Tests/images/l2rgb_read.bmp",
                "message": "not a modified file (status: FileStatus.ADDED)\n"
            },
            {
                "type": "NO_PATCH",
                "file_name": "Tests/images/l2rgb_read.bmp",
                "message": "File has no patch data.\n"
            },
            {
                "type": "NOT_MODIFIED",
                "file_name": "Tests/images/negative_size.ppm",
                "message": "not a modified file (status: FileStatus.ADDED)\n"
            },
            {
                "type": "NOT_MODIFIED",
                "file_name": "Tests/test_map.py",
                "message": "not a modified file (status: FileStatus.ADDED)\n"
            },
            {
                "type": "NOT_MODIFIED",
                "file_name": "docs/releasenotes/3.3.2.rst",
                "message": "not a modified file (status: FileStatus.ADDED)\n"
            }
        ]
    },
    "files_extension_stats": {
        ".rst": 3,
        ".c": 4,
        ".py": 9,
        ".ppm": 1
    },
    "file_number": 17,
    "removed_files_number": 0,
    "added_files_number": 0,
    "nb_lines_affected": 328,
    "private_key_files": [],
    "languages": [
        "C",
        "Python"
    ]
}